# Generated by Django 3.2.7 on 2021-10-24 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
                ('user', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 20, 36, 3, 43428))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
