# Generated by Django 3.2.7 on 2021-10-24 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 20, 39, 40, 106674)),
        ),
    ]
