# Generated by Django 3.2.7 on 2021-10-25 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 41, 43, 440389, tzinfo=utc)),
        ),
    ]
