# Generated by Django 3.2.7 on 2021-10-25 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 39, 33, 188643, tzinfo=utc)),
        ),
    ]
